[package]
name = "flight-booking-example"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
journey_dynamics = { path = "../.." }
uuid = { version = "1.19.0", features = ["serde", "v4"] }
cqrs-es = "0.4.12"

[lib]
name = "flight_booking"
path = "src/lib.rs"
